name: Update File

on:
  schedule:
    # This will run every day at 9 AM UTC
    - cron: '0 9 * * *'


jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "jzhang621@gmail.com"
          git config --global user.name "Jimmy Zhang"

      - name: Touch the file
        run: touch docs/data/jimmy.json.js docs/data/rodger.json.js

      - name: Commit and Push
        run: |
          git add .
          git commit --allow-empty -m "Automated update"
          git push
